/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;



@SuppressWarnings("java:S106")
public class App {
    public static void main(String... args) {
        HelloOtus hello = new HelloOtus();
        hello.fromHelloOtus();
    }
}
